name: 🐛 Bug Report
description: Signaler un bug ou un problème
title: "[Bug]: "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Merci de prendre le temps de signaler ce bug !

  - type: textarea
    id: description
    attributes:
      label: Description du bug
      description: Une description claire et concise du bug
      placeholder: Décrivez le bug...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Étapes pour reproduire
      description: Comment reproduire le comportement ?
      placeholder: |
        1. Aller sur '...'
        2. Cliquer sur '...'
        3. Scroller vers '...'
        4. Voir l'erreur
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Comportement attendu
      description: Qu'est-ce qui devrait se passer ?
      placeholder: Le comportement attendu...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Comportement actuel
      description: Qu'est-ce qui se passe actuellement ?
      placeholder: Le comportement actuel...
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Composant affecté
      description: Quelle partie de l'application est affectée ?
      options:
        - Frontend (Angular)
        - Backend (NestJS)
        - Base de données
        - Docker / Infrastructure
        - CI/CD
        - Documentation
        - Autre
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Sévérité
      description: Quelle est la sévérité du bug ?
      options:
        - Critique (bloque l'utilisation)
        - Majeure (fonctionnalité importante cassée)
        - Mineure (bug esthétique ou mineur)
        - Triviale (suggestion d'amélioration)
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environnement
      description: Informations sur votre environnement
      value: |
        - OS: [e.g. Windows 11, macOS 14, Ubuntu 22.04]
        - Browser: [e.g. Chrome 120, Firefox 121, Safari 17]
        - Node.js: [e.g. 20.10.0]
        - Version: [e.g. v1.0.0]
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs / Messages d'erreur
      description: Si applicable, copier les logs ou messages d'erreur
      render: shell
      placeholder: |
        Coller les logs ici...

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Si applicable, ajouter des screenshots
      placeholder: |
        Glisser-déposer les images ici...

  - type: textarea
    id: additional
    attributes:
      label: Contexte additionnel
      description: Toute autre information pertinente
      placeholder: Informations supplémentaires...

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Avez-vous vérifié les points suivants ?
      options:
        - label: J'ai recherché dans les issues existantes
          required: true
        - label: J'ai vérifié la documentation
          required: true
        - label: Je peux reproduire ce bug de manière consistante
          required: false
